version: '3.8'

services:
  # Infrastructure Services
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: mindcanvas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Microservices
  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "8000:8000"
    depends_on:
      - kafka
      - redis
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - REDIS_URL=redis://redis:6379

  auth-service:
    build:
      context: ./auth-service
    ports:
      - "8001:8001"
    depends_on:
      - postgres
      - kafka
      - redis
    environment:
      - DATABASE_URL=postgresql://postgres:1974@localhost:5432/mindcanvas_micro
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - REDIS_URL=redis://redis:6379

  user-service:
    build:
      context: ./user-service
    ports:
      - "8002:8002"
    depends_on:
      - postgres
      - kafka
      - redis
    environment:
      - DATABASE_URL=postgresql://postgres:1974@localhost:5432/mindcanvas_micro
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - REDIS_URL=redis://redis:6379

  search-service:
    build:
      context: ./search-service
    ports:
      - "8003:8003"
    depends_on:
      - postgres
      - kafka
      - redis
    environment:
      - DATABASE_URL=postgresql://postgres:1974@localhost:5432/mindcanvas_micro
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - REDIS_URL=redis://redis:6379
      - TAVILY_API_KEY=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
      - TAVILY_PROFILE=excess-booby-2DGYu0

  image-service:
    build:
      context: ./image-service
    ports:
      - "8004:8004"
    depends_on:
      - postgres
      - kafka
      - redis
    environment:
      - DATABASE_URL=postgresql://postgres:1974@localhost:5432/mindcanvas_micro
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - REDIS_URL=redis://redis:6379
      - FLUX_API_KEY=54945398-acdb-4b35-975e-595c7fa33ed1

  dashboard-service:
    build:
      context: ./dashboard-service
    ports:
      - "8005:8005"
    depends_on:
      - postgres
      - kafka
      - redis
    environment:
      - DATABASE_URL=postgresql://postgres:1974@localhost:5432/mindcanvas_micro
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - REDIS_URL=redis://redis:6379

  # Frontend
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - api-gateway
    environment:
      - REACT_APP_API_URL=http://localhost:8000

volumes:
  postgres_data:
