# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\x12\x04\x61uth\"%\n\x14ValidateTokenRequest\x12\r\n\x05token\x18\x01 \x01(\t\"U\n\x15ValidateTokenResponse\x12\r\n\x05valid\x18\x01 \x01(\x08\x12\x0f\n\x07user_id\x18\x02 \x01(\x05\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\r\n\x05\x65rror\x18\x04 \x01(\t\"G\n\x11\x43reateUserRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\x11\n\tfull_name\x18\x03 \x01(\t\"E\n\x12\x43reateUserResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07user_id\x18\x02 \x01(\x05\x12\r\n\x05\x65rror\x18\x03 \x01(\t\"!\n\x0eGetUserRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\"b\n\x0fGetUserResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x11\n\tfull_name\x18\x03 \x01(\t\x12\x12\n\ncreated_at\x18\x04 \x01(\t\x12\r\n\x05\x65rror\x18\x05 \x01(\t2\xd0\x01\n\x0b\x41uthService\x12H\n\rValidateToken\x12\x1a.auth.ValidateTokenRequest\x1a\x1b.auth.ValidateTokenResponse\x12?\n\nCreateUser\x12\x17.auth.CreateUserRequest\x1a\x18.auth.CreateUserResponse\x12\x36\n\x07GetUser\x12\x14.auth.GetUserRequest\x1a\x15.auth.GetUserResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_VALIDATETOKENREQUEST']._serialized_start=20
  _globals['_VALIDATETOKENREQUEST']._serialized_end=57
  _globals['_VALIDATETOKENRESPONSE']._serialized_start=59
  _globals['_VALIDATETOKENRESPONSE']._serialized_end=144
  _globals['_CREATEUSERREQUEST']._serialized_start=146
  _globals['_CREATEUSERREQUEST']._serialized_end=217
  _globals['_CREATEUSERRESPONSE']._serialized_start=219
  _globals['_CREATEUSERRESPONSE']._serialized_end=288
  _globals['_GETUSERREQUEST']._serialized_start=290
  _globals['_GETUSERREQUEST']._serialized_end=323
  _globals['_GETUSERRESPONSE']._serialized_start=325
  _globals['_GETUSERRESPONSE']._serialized_end=423
  _globals['_AUTHSERVICE']._serialized_start=426
  _globals['_AUTHSERVICE']._serialized_end=634
# @@protoc_insertion_point(module_scope)
